go_import_path: github.com/zijung/viper

language: go
go:
  - 1.10.x
  - 1.11.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

after_success:
  - go get -u -d github.com/zijung/hugo
  - cd $GOPATH/src/github.com/zijung/hugo && make && ./hugo -s docs && cd -

sudo: false
